import express from "express";

const app = express();

// 상품 구매하기
app.post("/product/buy", function (req, res) {
    // 1. 가진 돈을 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...

    // 2. 판매여부 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...

    // 3. 상품 구매하는 코드
    // if(돈 있음 && 판매 중)
    res.send("상품을 구매합니다.");
});

// 상품 환불하기
app.post("/product/refund", function (req, res) {
    // 1. 판매 여부 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...
    // ...
    // ...

    // 2. 상품 환불하는 코드
    // if(판매완료)
    res.send("상품을 환불합니다.");
});

app.listen(3000);
