// cash.service.js

export class CashService {
    checkValue = () => {
        // 1. 가진돈 검증하는 코드(10줄)
        console.log("현금 검증");
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    };
}
