// product.service.js

export class ProductService {
    checkSoldout = () => {
        // 판매여부 검증하는 코드(10줄)
        console.log("판매 검증");
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    };
}

